<div class="container category-boxes-wrapper">
    <div class="row">
        <div class="col-md-3 col-xs-12 col-sm-6 black-box">
            <h2>fashion</h2>
            <h3>BIG sale <span class="up-to">up to</span> <span class="percentage">30%</span> <span class="off">off</span></h3>
            <a class="buy-now-btn" href="<?=$block->getUrl("sale.html");?>">Buy Now</a> <img class="support-img" src="<?=$block->getViewFileUrl("images/media/big-sale-img.png");?>" alt="" /></div>
        <div class="col-md-3 col-xs-12 col-sm-6 pink-box middle-two-box">
            <h2 class="text-right">for her</h2>
            <h3 class="text-right">Best<br /> Selling Deals</h3>
            <a class="buy-now-btn" href="<?=$block->getUrl("women.html");?>">Buy Now</a> <img class="support-img" src="<?=$block->getViewFileUrl("images/media/category-girl-img.png");?>" alt="" /></div>
        <div class="col-md-3 col-xs-12 col-sm-6 light-box middle-two-box">
            <h2 class="text-right">for him</h2>
            <h3 class="text-right">Best<br /> Selling Deals</h3>
            <a class="buy-now-btn" href="<?=$block->getUrl("men.html");?>">Buy Now</a> <img class="support-img" src="<?=$block->getViewFileUrl("images/media/category-men-img.png");?>" alt="" /></div>
        <div class="col-md-3 col-xs-12 col-sm-6 gray-box">
            <h2 class="text-center">Deals + <span class="promos">promos</span></h2>
            <h3 class="text-center">Limited sales in category</h3>
            <a class="buy-now-btn" href="<?=$block->getUrl("sale.html");?>">Buy Now</a> <img class="support-img" src="<?=$block->getViewFileUrl("images/media/promo-img.png");?>" alt="" /></div>
    </div>
</div>