<div class="container-fluid">
    <div class="row footer-contact-info">
        <div class="container">
            <div class="row">
                <div class="col-sm-3"><img class="img-responsive" src="<?=$block->getViewFileUrl("images/media/logo.png");?>" alt="" /></div>
                <div class="col-sm-9">
                    <h2>Contact Information</h2>
                    <h3><span><strong>Address:</strong> F-48 A Shastri Nagar, New Delhi 10052</span> <span><strong>Phone:</strong> <a href="tel:09999619050">(+91) 999-961-9050</a></span> <span><strong>Email:</strong> <a href="mailto:info@czonetechnologies.com">info@czonetechnologies.com</a></span></h3>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row smo-info">
        <div class="container">
            <div class="row">
                <div class="col-md-6"><span class="title">We accept:</span> <img src="<?=$block->getViewFileUrl("images/media/pay-options.png");?>" alt="" width="359" height="28" /></div>
                <div class="col-md-6 text-right"><span class="title">Follow us:</span> <a class="smo-ellipse smo-ellipse facebook" href="#">&nbsp;</a> <a class="smo-ellipse twitter" href="#">&nbsp;</a> <a class="smo-ellipse in" href="#">&nbsp;</a></div>
            </div>
        </div>
    </div>
</div>