<div class="home-page-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-xs-12 col-sm-4"><img class="support-icon" src="<?=$block->getViewFileUrl("images/media/shipping-icon.png");?>" alt="" />
                <div class="content">
                    <h3>FREE SHIPPING &amp; RETURN</h3>
                    <h4>Free shipping on all orders over $99.</h4>
                </div>
            </div>
            <div class="col-md-4 col-xs-12 col-sm-4"><img class="support-icon" src="<?=$block->getViewFileUrl("images/media/currency-icon.png");?>" alt="" />
                <div class="content">
                    <h3>MONEY BACK GUARANTEE</h3>
                    <h4>100% money back guarantee.</h4>
                </div>
            </div>
            <div class="col-md-4 col-xs-12 col-sm-4"><img class="support-icon" src="<?=$block->getViewFileUrl("images/media/online-support-icon.png");?>" alt="" />
                <div class="content">
                    <h3>ONLINE SUPPORT 24/7</h3>
                    <h4>Lorem ipsum dolor sit amet.</h4>
                </div>
            </div>
        </div>
    </div>
</div>