<div class="slide-wrapper">
    <div class="slide-item"><span class="next-btn jsNextBtn" title="Next"><label>Next</label></span> <span class="prev-btn jsPrevBtn" title="Prev"><label>Prev</label></span> <img class="img-responsive" src="<?=$block->getViewFileUrl("images/media/slide1.jpg");?>" alt="" />
        <div class="slide-content">
            <div class="owl-carousel">
                <div>
                    <h3>Brand New Collection</h3>
                    <h1>Street Winter Style</h1>
                    <h3>Special discount this week</h3>
                    <a class="buy-now-btn" href="<?=$block->getUrl("kids/pullovers-cardigans.html");?>">Buy Now</a>
                </div>
                <div>
                    <h3>Fashion Collection</h3>
                    <h1>Street Designer Style</h1>
                    <h3>Special discount on Fashion Items</h3>
                    <a class="buy-now-btn" href="<?=$block->getUrl("designers.html");?>">Buy Now</a>
                </div>
                <div>
                    <h3>Men Collection all Season</h3>
                    <h1>Men Fashion Style</h1>
                    <h3>Special deal on Men Collection all Season</h3>
                    <a class="buy-now-btn" href="<?=$block->getUrl("men.html");?>">Buy Now</a>
                </div>
            </div>
        </div>
    </div>
</div>